[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
idevice = { version = "0.1.29", features = ["usbmuxd", "tcp"] }
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }